# Generated by Django 3.2.6 on 2021-08-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='title',
        ),
    ]
