"""contacts table

Revision ID: 5344c1702825
Revises: 
Create Date: 2021-07-20 11:45:05.425765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5344c1702825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mail', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('birthday', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_birthday'), 'contact', ['birthday'], unique=False)
    op.create_index(op.f('ix_contact_contact_name'), 'contact', ['contact_name'], unique=True)
    op.create_index(op.f('ix_contact_mail'), 'contact', ['mail'], unique=True)
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_mail'), table_name='contact')
    op.drop_index(op.f('ix_contact_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_birthday'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
